#!/usr/bin/env bash

[[ $# -ne 2 ]] && echo "[error] Wrong Usage. '$ $0 <serverName|serverIP>'" && exit 1

SERVER_KEYWORD="$1"
SERVER_LIST_PATH="$2"

[[ ! -f "${SERVER_LIST_PATH}" ]] && echo "[ERROR] Server list path (${SERVER_LIST_PATH}) is missing." && exit 1

######################################################## main

unset _SERVER_ENTRY

if [[ $(echo "${SERVER_KEYWORD:0:1}" | grep -c '[0-9]') -ne 0 ]]; then
  ## keyword is IP Address
  _SERVER_ENTRY=$(cat "${SERVER_LIST_PATH}" | awk '{if ($5=="'$SERVER_KEYWORD'" || $6=="'$SERVER_KEYWORD'") print $0}' | sed 's/ \s*/  /g')

else
  ## domain name
  _SERVER_ENTRY=$(cat "${SERVER_LIST_PATH}" | awk '{if ($2=="'$SERVER_KEYWORD'") print $0}' | sed 's/ \s*/  /g')

fi

[[ -z "${_SERVER_ENTRY}" ]] && _SERVER_ENTRY="There was no specific match. Here is list of all partial matchs, retry with more accurate match.

"$(cat "${SERVER_LIST_PATH}" | grep "${SERVER_KEYWORD}" | awk '{print $2}' | sort -d -b -f -i | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/, /gi')

[[ -z "${_SERVER_ENTRY}" ]] && echo "[ERROR] either your provided name/ip isn't complete or it doen't exist in our records" && exit 1

echo "${_SERVER_ENTRY}"

########################################################
